QQuickPicture: add missing QDebug include
On windows7x86wince70embeddedarmmsvc2008:
qquickpicture.cpp(118) : error C2027: use of undefined type 'QDebug'

Change-Id: I81efd9b922b8642892f89aca59b768d1b411739b
Reviewed-by: Frederik Gladhorn <frederik.gladhorn@theqtcompany.com>